apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: alanx30/ecommercemodulo_consumer:latest
          env:
            - name: HOSTRABBITMQ
              value: amqp://rabbit-0.rabbit
            - name: DB_URI
              value: mongodb://mongo-0.mongo/moduloecommerce