apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: rabbit
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  serviceName: rabbit
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rabbit
    spec:
      containers:
        - image: rabbitmq:3.9.13-management
          imagePullPolicy: IfNotPresent
          name: rabbit
          ports:
            - containerPort: 5672
              name: web
              protocol: TCP
            - containerPort: 15672
              name: management
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30 
  updateStrategy:
    type: OnDelete